### ISSUE TITLE
error when converting from biom to spf with this script

### ISSUE THREAD

**Issue by jennomics** [mlangill/get_mgrast_data#1]
Hi Morgan!

I am trying to compare two metagenomes: one predicted by picrust and one real one from the same DNA sample. So, I downloaded the KO assingments in .biom format from MG-RAST and I created a .biom table per the picrust instructions. I then merged the two .biom tables. The merged .biom table seems to serve well as input into various qiime scripts, so I assume there are no problems with it.

Now, I want to use STAMP with this merged .biom table, and when I run this script to do it, I get the error below. I am running in my macqiime environment, btw.

Traceback (most recent call last):
  File "biom_to_stamp.py", line 85, in <module>
    main()
  File "biom_to_stamp.py", line 56, in main
    max_len_metadata = max(len(p[metadata_name]) for p in table.ObservationMetadata)
  File "biom_to_stamp.py", line 56, in <genexpr>
    max_len_metadata = max(len(p[metadata_name]) for p in table.ObservationMetadata)
TypeError: object of type 'NoneType' has no len()

Thanks!
Jenna

**Comment by mlangill** [comment]
This error is a result of the metadata name not being found in the BIOM file either because it is the wrong one or the BIOM table contains no observation metadata. I have added additional checks to the script and more documentation usage statements in this commit: 68430928059ef0fa0c51d895bb986f6d94233367
